Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),]

pizzas/urls.py
from django.urls import path
from . import views
app_name = 'pizzas'
urlpatterns = [
    path('', views.index, name='index'),
    path('Pizzas/', views.Pizzas, name= 'Pizzas'),
    path('topping/<int:Pizza_id>/', views.topping, name= 'topping'),   
    path('pizzacomments/<int:Pizza_id>/', views.pizzacomments, name= 'pizzacomments')   
   ]

pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    """A Pizza Type."""
    name = models.CharField(max_length=200)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

class Topping(models.Model):
    """A topic the user is learning about."""
    name = models.CharField(max_length=200)
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

class pizza_comment(models.Model):
    Pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.text[:50]}..." 
        

pizzas/forms.py
from django import forms

from .models import pizza_comment

class Pizza_commentForm(forms.ModelForm):
    class Meta:
        model = pizza_comment
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza
from .forms import Pizza_commentForm
# Create your views here.
def index(request):
    """The home page for pizzas."""
    return render(request, 'pizzas/index.html') 

def Pizzas(request):
    "Display all Pizzas"
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/Pizzas.html',context)

def topping(request,Pizza_id):
    "Display all Pizzas"
    Pizas = Pizza.objects.get(id=Pizza_id)
    toppings =Pizas.topping_set.order_by('name')
    comments = Pizas.pizza_comment_set.all()
    context = {'Pizas': Pizas, 'toppings': toppings,'comments': comments}
    return render(request, 'pizzas/pizza.html',context)

def pizzacomments(request,Pizza_id):
    pizza = Pizza.objects.get(id=Pizza_id)
    if request.method != 'POST':
        form = Pizza_commentForm()
    else:
        form = Pizza_commentForm(data=request.POST)
        if form.is_valid():
            pizza_comments = form.save(commit=False)
            pizza_comments.Pizza = pizza
            pizza_comments.save()
            return redirect('pizzas:topping', Pizza_id=Pizza_id)
    context = {'pizza': pizza, 'form': form}
    return render(request, 'pizzas/new_comment.html', context)

pizzas/templates/pizzas/Pizzas.html
{% extends "pizzas/base.html" %}
{% block content %}
  <p>Pizzas</p>
  <ul>
      {% for pizza in pizzas %}
       <li>
         <a href="{% url 'pizzas:topping' pizza.id %}">{{ pizza }}</a>
       </li>
 
      {% empty %}
        <li> No Pizzas have been added yet.</li>
      {% endfor %}
   
  </ul>

{% endblock content %}

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizerria</a>
    <a href="{% url 'pizzas:Pizzas' %}"> Pizzas</a> 

</p>
{% block content %}{% endblock content %} 

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% block content %}
    <p>Pizzeria provides information about the Pizzas Served and the available Toppings.</p> 
{% endblock content %} 

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}
{% block content %}

<p><a href="{url 'pizzas:topping' Pizas.id %}">{{pizza}}</a></p>

<p>Drop a comment::</p>
<form action="{% url 'pizzas:pizzacomments' pizza.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Add Comment</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}
{% block content %}
{% load static %}
<p>Pizzas : {{ Pizas }}</p>
<img src="{% static 'gallery/Hawain.png' width=50 %}">
<p>Toppings: </p>
<ul>
    {% for topping in toppings %}
    <li>
        <p>{{ topping.name|linebreaks }}</p>
     </li>
    {% empty %}
      <li> There are no topings for this Pizza.</li>
    {% endfor %}
</ul>



<p>
  <a href="{% url 'pizzas:pizzacomments' Pizas.id %}">Add a Comment</a>
</p>
<p>Comments: </p>
<ul>
  {% for Comment in comments %}
  <li>
    <p>{{ Comment.text|linebreaks }}</p>
  </li>
  {% empty %}
  <li> There are no comments for this Pizza.</li>
  {% endfor %}
</ul>





{% endblock content %}